### ISSUE TITLE
Purpose of this tool

### ISSUE THREAD

**Issue by uswoods** [TNOCS/geojson-tile-server#1]
I'm really curious: What should I do with with GeoJSON tiles?

Am I right, that geojson-tile-server is reading in a big geojson and serving small _geojson_ extracts? Not PNGs?

**Comment by erikvullings** [comment]
Yes, you are correct. The server loads a big geojson, and cuts it into pieces (leaving out some details at the lower zoom levels). The client is then able to retrieve only the parts it needs. For example, I've used it for a HoloLens map app (WorldExplorer, also on github), which is basically a smartphone and not very powerful, so it would only load the tiles that were needed to render the map.
