### ISSUE TITLE
MVT's not compatible with Mapbox GL JS.

### ISSUE THREAD

**Issue by Craytor** [TNOCS/geojson-tile-server#2]
The .mvt tiles appear to not be compatible with Mapbox GL JS as I am getting "Unimplemented type: 3" errors.

Has this been tested with Mapbox GL JS before? If so any tips to complete this?

**Comment by erikvullings** [comment]
I've created this project 2yrs ago, and haven't touched it since then. Based on the error you are getting, I assume that the current version of Mapbox uses a newer type. 

Since this is actually only a thin wrapper around two mapbox npm packages, [vt-pbf](https://www.npmjs.com/package/vt-pbf) and [geojson-vt](https://www.npmjs.com/package/geojson-vt), could you try the following: update the dependencies in package.json to their latest version (3.1.1. and 3.2.1, respectively) and try it again.

**Comment by Craytor** [comment]
Thanks for the response! I've tried to update both and am still being faced with the same error.

**Comment by Craytor** [comment]
Update: I created another nodejs app and had the same exact issue. I found out that some how the issue is being caused by how node is sending data over the api.  In my example app, this is essentially all I have and it is working.
```
app.get('/:z/:x/:y.pbf', (req, res) => {
	const z = +req.params['z'];
	const x = +req.params['x'];
	const y = +req.params['y'];

	var tile = tileindex.getTile(z, x, y)

	var buff = vtpbf.fromGeojsonVt({ 'alertsLayer': tile }, {version: 2})
	fs.writeFileSync(z + '-' + x + '-' + y + '.pbf', buff)
	res.sendFile(z + '-' + x + '-' + y + '.pbf', { root : __dirname});
});
```
If I try doing res.send(buff), in my network tab I get what looks to be an array (with just numbers) but it's not suppose to be one. I then tried saving as a file, and then sending the file and it works as expected - I've got polygons now on my map! Now I'm going to try to eliminate the writeFile and then sendFile to hopefully make it one step and cut down on IO.

**Comment by erikvullings** [comment]
Good to hear that you are getting closer.
Perhaps you can create a readstream and send this in the response like [here](https://stackoverflow.com/a/17818492/319711).

**Comment by erikvullings** [comment]
I've just updated the current version, and tested it with a 5Mb GeoJSON containing building contours from the city Amersfoort in The Netherlands. Please checkout the Readme (source section - clone or fork the repo, install dependencies, and run it). The playground contains a Mapbox example using the mvt tiles (but requires you to insert your own Mapbox key).

If it is not working, feel free to re-open it.

**Comment by Craytor** [comment]
Aha, better.

Question though, in my example I done something like:
```
res.send(Buffer.from(vtpbf.fromGeojsonVt({ 'layer': tile })));
```
Is there an advantage to doing it this way over what I have?
```
const buff = vtpbf.fromGeojsonVt({ all: tile });
const buffStream = new stream.PassThrough();
buffStream.end(buff);
buffStream.pipe(res);
```

**Comment by erikvullings** [comment]
Nice work! A lot shorter, and no need to import stream. I've updated the code with your version, thanks!
