### ISSUE TITLE
unimplemented type: 3

### ISSUE THREAD

**Issue by alsconsulting** [TNOCS/geojson-tile-server#6]
love the project! But having a few issues when using the .mvt option, eg. http://localhost:8123/Gardens/18/242233/150829.mvt produces a protobuf response which I am consuming using leaflet.js

I get an error saying unimplemented type:3 which when I google seems to be related to a zipped pbf file, how can I turn off this zip compression?

**Comment by duckyb** [comment]
I'm also having this issue, looking for a way to disable compression.

**Comment by erikvullings** [comment]
@duckyb Can you please give me some data and a more detailed description to reproduce your problem, so I can have a look. Thanks.

**Comment by duckyb** [comment]
### Minimal reproduction download
[unimplemented-type-3.zip](https://github.com/TNOCS/geojson-tile-server/files/5180452/unimplemented-type-3.zip)
### Tools used
+ [Leaflet](https://leafletjs.com/) (loads the map)
+ [Leaflet.VectorGrid Plugin](https://leaflet.github.io/Leaflet.VectorGrid/vectorgrid-api-docs.html) (loads the vector grid from geojson-tile-server)
+ geojson-tile-server
### How to use
+ Unzip the folder
+ Launch `geojson-tile-server` in the root dir (i have it installed globally)
+ Launch `index.html` with Chrome
### Screenshot of the error
![image](https://user-images.githubusercontent.com/27895007/92337458-33a85d80-f0aa-11ea-9ad4-7965052e5445.png)

---

@erikvullings There you go!

Also, related issue: https://github.com/Leaflet/Leaflet.VectorGrid/issues/121

**Comment by erikvullings** [comment]
@duckyb @alsconsulting Thanks for uploading the example. I've just released a fix and it is working on my side. See the zip file for the (minor) changes that I've applied to your example.

![image](https://user-images.githubusercontent.com/3140667/92468640-c55fba00-f1d3-11ea-8df0-52cbff2d3684.png)

[unimplemented-type-3.zip](https://github.com/TNOCS/geojson-tile-server/files/5187863/unimplemented-type-3.zip)

**Comment by duckyb** [comment]
@erikvullings Thank you for the fix. Much appreciated!
